# Generated by Django 2.2.5 on 2019-09-20 10:37

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', audio.models.AudioFileField(null=True, upload_to='audio/')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('prediction', models.CharField(max_length=20, null=True)),
                ('response', models.BooleanField(default=False)),
            ],
        ),
    ]
